package com.jlanzasg.novabank.cliente.integration;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class ClienteFullIntegrationTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///cliente_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    private WebTestClient webTestClient;

    @LocalServerPort
    private int port;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchema() {
        this.webTestClient = WebTestClient.bindToServer().baseUrl("http://localhost:" + port).build();
        databaseClient.sql("DROP TABLE IF EXISTS clientes").then().block();
        databaseClient.sql("CREATE TABLE clientes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dni VARCHAR(20) UNIQUE NOT NULL, nombre VARCHAR(100) NOT NULL, apellidos VARCHAR(120) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, telefono VARCHAR(20) UNIQUE NOT NULL, fecha TIMESTAMP)").then().block();
    }

    @Test
    void createThenReadThenDelete_FullFlowAgainstRealStack() {
        webTestClient.post()
                .uri("/clientes")
                .header("Content-Type", "application/json")
                .bodyValue("""
                        {
                          "dni": "12345678A",
                          "nombre": "Laura",
                          "apellidos": "Sanchez",
                          "email": "laura@test.com",
                          "telefono": "611222333"
                        }
                        """)
                .exchange()
                .expectStatus().isCreated()
                .expectBody()
                .jsonPath("$.id").isNumber()
                .jsonPath("$.dni").isEqualTo("12345678A");

        webTestClient.get()
                .uri("/clientes/dni/12345678A")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$.email").isEqualTo("laura@test.com");

        webTestClient.get()
                .uri("/clientes")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$[0].dni").isEqualTo("12345678A");

        webTestClient.delete()
                .uri("/clientes/1")
                .exchange()
                .expectStatus().isNoContent();

        webTestClient.get()
                .uri("/clientes/1")
                .exchange()
                .expectStatus().isNotFound();
    }
}
