package com.jlanzasg.novabank.operacion.repository;

import com.jlanzasg.novabank.operacion.model.Movimiento;
import com.jlanzasg.novabank.operacion.model.TipoMovimiento;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

import java.time.LocalDateTime;

@SpringBootTest
@ActiveProfiles("test")
class OperacionRepositoryTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///operacion_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    @Autowired
    private OperacionRepository operacionRepository;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchema() {
        databaseClient.sql("DROP TABLE IF EXISTS movimientos").then().block();
        databaseClient.sql("CREATE TABLE \"movimientos\" (\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"IBAN\" VARCHAR(40) NOT NULL, \"TIPO\" VARCHAR(50) NOT NULL, \"CANTIDAD\" DOUBLE PRECISION NOT NULL, \"FECHA\" TIMESTAMP)")
                .then().block();
    }

    @Test
    void findByIbanOrderByFechaDesc_ReturnsRows() {
        Flux.concat(
                operacionRepository.save(Movimiento.builder().iban("ES1").tipo(TipoMovimiento.DEPOSITO).cantidad(10.0).fecha(LocalDateTime.now().minusMinutes(1)).build()),
                operacionRepository.save(Movimiento.builder().iban("ES1").tipo(TipoMovimiento.RETIRO).cantidad(5.0).fecha(LocalDateTime.now()).build())
        ).blockLast();

        StepVerifier.create(operacionRepository.findByIbanOrderByFechaDesc("ES1"))
                .expectNextCount(2)
                .verifyComplete();
    }

    @Test
    void findByIbanAndFechaBetweenOrderByFechaDesc_FiltersByRange() {
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES2', 'DEPOSITO', 10.0, TIMESTAMP '2026-01-01 10:00:00')").then().block();
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES2', 'RETIRO', 20.0, TIMESTAMP '2026-01-10 10:00:00')").then().block();
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES2', 'DEPOSITO', 30.0, TIMESTAMP '2026-01-12 10:00:00')").then().block();

        StepVerifier.create(operacionRepository.findByIbanAndFechaBetweenOrderByFechaDesc(
                        "ES2",
                        LocalDateTime.of(2026, 1, 9, 0, 0),
                        LocalDateTime.of(2026, 1, 12, 23, 59)))
                .expectNextMatches(m -> m.getCantidad().equals(30.0))
                .expectNextMatches(m -> m.getCantidad().equals(20.0))
                .verifyComplete();
    }

    @Test
    void findByIbanAndFechaBetweenOrderByFechaDesc_WhenNoRows_ReturnsEmpty() {
        StepVerifier.create(operacionRepository.findByIbanAndFechaBetweenOrderByFechaDesc(
                        "ES-EMPTY",
                        LocalDateTime.of(2026, 1, 1, 0, 0),
                        LocalDateTime.of(2026, 1, 2, 0, 0)))
                .verifyComplete();
    }
}
