package com.jlanzasg.novabank.cuenta.integration;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class CuentaFullIntegrationTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///cuenta_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    private WebTestClient webTestClient;

    @LocalServerPort
    private int port;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchemaAndData() {
        this.webTestClient = WebTestClient.bindToServer().baseUrl("http://localhost:" + port).build();
        databaseClient.sql("DROP TABLE IF EXISTS \"cuentas\"").then().block();
        databaseClient.sql("CREATE TABLE \"cuentas\" (\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"IBAN\" VARCHAR(40) UNIQUE NOT NULL, \"BALANCE\" DOUBLE PRECISION, \"CLIENTE_ID\" BIGINT NOT NULL, \"FECHA\" TIMESTAMP, \"VERSION\" BIGINT)").then().block();
        databaseClient.sql("INSERT INTO \"cuentas\" (\"IBAN\", \"BALANCE\", \"CLIENTE_ID\", \"VERSION\") VALUES ('ES91210000000000000001', 100.0, 7, 0)").then().block();
        databaseClient.sql("INSERT INTO \"cuentas\" (\"IBAN\", \"BALANCE\", \"CLIENTE_ID\", \"VERSION\") VALUES ('ES91210000000000000002', 20.0, 7, 0)").then().block();
        databaseClient.sql("INSERT INTO \"cuentas\" (\"IBAN\", \"BALANCE\", \"CLIENTE_ID\", \"VERSION\") VALUES ('ES91210000000000000003', 5.0, 9, 0)").then().block();
    }

    @Test
    void readAndUpdateBalance_FullFlowAgainstRealStack() {
        webTestClient.get()
                .uri("/cuentas/cliente/7")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$[0].id").isNumber();

        webTestClient.put()
                .uri("/cuentas/iban/ES91210000000000000001/saldo?nuevoSaldo=250.5")
                .exchange()
                .expectStatus().isOk();

        Double balance = databaseClient.sql("SELECT \"BALANCE\" FROM \"cuentas\" WHERE \"IBAN\"='ES91210000000000000001'")
                .map((row, metadata) -> row.get(0, Double.class))
                .one()
                .block();

        org.assertj.core.api.Assertions.assertThat(balance).isEqualTo(250.5);
    }
}
