package com.jlanzasg.novabank.operacion.integration;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class OperacionFullIntegrationTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///operacion_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    private WebTestClient webTestClient;

    @LocalServerPort
    private int port;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchemaAndData() {
        this.webTestClient = WebTestClient.bindToServer().baseUrl("http://localhost:" + port).build();
        databaseClient.sql("DROP TABLE IF EXISTS \"movimientos\"").then().block();
        databaseClient.sql("CREATE TABLE \"movimientos\" (\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"IBAN\" VARCHAR(40) NOT NULL, \"TIPO\" VARCHAR(50) NOT NULL, \"CANTIDAD\" DOUBLE PRECISION NOT NULL, \"FECHA\" TIMESTAMP)").then().block();
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES91210000000000000001', 'DEPOSITO', 100.0, TIMESTAMP '2026-05-01 09:00:00')").then().block();
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES91210000000000000001', 'RETIRO', 20.0, TIMESTAMP '2026-05-03 12:00:00')").then().block();
        databaseClient.sql("INSERT INTO \"movimientos\" (\"IBAN\", \"TIPO\", \"CANTIDAD\", \"FECHA\") VALUES ('ES91210000000000000001', 'DEPOSITO', 50.0, TIMESTAMP '2026-05-06 18:00:00')").then().block();
    }

    @Test
    void getMovimientos_WithAndWithoutDateRange_UsesRealStack() {
        webTestClient.get()
                .uri("/operaciones/movimientos/ES91210000000000000001")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$[0].tipoMovimiento").isEqualTo("DEPOSITO")
                .jsonPath("$[1].tipoMovimiento").isEqualTo("RETIRO")
                .jsonPath("$[2].tipoMovimiento").isEqualTo("DEPOSITO");

        webTestClient.get()
                .uri("/operaciones/movimientos/ES91210000000000000001?fechaInicio=2026-05-02&fechaFin=2026-05-04")
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$[0].tipoMovimiento").isEqualTo("RETIRO");
    }
}
