package com.jlanzasg.novabank.cliente.repository;

import com.jlanzasg.novabank.cliente.model.Cliente;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

@SpringBootTest
@ActiveProfiles("test")
class ClienteRepositoryTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///cliente_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    @Autowired
    private ClienteRepository clienteRepository;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchema() {
        databaseClient.sql("DROP TABLE IF EXISTS clientes").then().block();
        databaseClient.sql("CREATE TABLE clientes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dni VARCHAR(20) UNIQUE NOT NULL, nombre VARCHAR(100) NOT NULL, apellidos VARCHAR(120) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, telefono VARCHAR(20) UNIQUE NOT NULL, fecha TIMESTAMP)")
                .then()
                .block();
    }

    @Test
    void findConflictos_WhenDniExists_ReturnsDni() {
        Cliente cliente = Cliente.builder()
                .dni("12345678A")
                .nombre("Nombre")
                .apellidos("Apellido")
                .email("mail@test.com")
                .telefono("600111222")
                .build();

        clienteRepository.save(cliente).block();

        StepVerifier.create(clienteRepository.findConflictos("12345678A", "otro@test.com", "699999999"))
                .expectNext("DNI")
                .verifyComplete();
    }

    @Test
    void findByDni_WhenNotFound_ReturnsEmpty() {
        StepVerifier.create(clienteRepository.findByDni("00000000Z"))
                .verifyComplete();
    }

    @Test
    void findAll_WhenRowsExist_ReturnsRows() {
        Flux.concat(
                clienteRepository.save(Cliente.builder().dni("11111111A").nombre("Aaa").apellidos("Uno").email("a1@test.com").telefono("611111111").build()),
                clienteRepository.save(Cliente.builder().dni("22222222B").nombre("Bbb").apellidos("Dos").email("b2@test.com").telefono("622222222").build())
        ).blockLast();

        StepVerifier.create(clienteRepository.findAll())
                .expectNextCount(2)
                .verifyComplete();
    }
}
