server:
  port: 8888 # Puerto estándar mundial para Config Server

spring:
  application:
    name: config-server
  profiles:
    active: native # Usamos el perfil "native" para leer los archivos de configuración desde el sistema de archivos local
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/ # Ubicación de los archivos de configuración dentro del classpath