package com.jlanzasg.novabank.cuenta.repository;

import com.jlanzasg.novabank.cuenta.model.Cuenta;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

@SpringBootTest
@ActiveProfiles("test")
class CuentaRepositoryTest {

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry registry) {
        registry.add("spring.r2dbc.url", () -> "r2dbc:h2:mem:///cuenta_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false");
        registry.add("spring.r2dbc.username", () -> "sa");
        registry.add("spring.r2dbc.password", () -> "");
    }

    @Autowired
    private CuentaRepository cuentaRepository;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setupSchema() {
        databaseClient.sql("DROP TABLE IF EXISTS cuentas").then().block();
        databaseClient.sql("CREATE TABLE \"cuentas\" (\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"IBAN\" VARCHAR(40) UNIQUE NOT NULL, \"BALANCE\" DOUBLE PRECISION, \"CLIENTE_ID\" BIGINT NOT NULL, \"FECHA\" TIMESTAMP, \"VERSION\" BIGINT)")
                .then().block();
    }

    @Test
    void findByIban_WhenExists_ReturnsCuenta() {
        Cuenta cuenta = Cuenta.builder().iban("ES91210000000000000001").balance(100.0).clienteId(5L).build();
        cuentaRepository.save(cuenta).block();

        StepVerifier.create(cuentaRepository.findByIban("ES91210000000000000001"))
                .expectNextMatches(c -> c.getClienteId().equals(5L))
                .verifyComplete();
    }

    @Test
    void findAllByClienteId_ReturnsOnlyClientRows() {
        Flux.concat(
                cuentaRepository.save(Cuenta.builder().iban("ES91210000000000000002").balance(10.0).clienteId(7L).build()),
                cuentaRepository.save(Cuenta.builder().iban("ES91210000000000000003").balance(20.0).clienteId(7L).build()),
                cuentaRepository.save(Cuenta.builder().iban("ES91210000000000000004").balance(30.0).clienteId(8L).build())
        ).blockLast();

        StepVerifier.create(cuentaRepository.findAllByClienteId(7L))
                .expectNextCount(2)
                .verifyComplete();
    }
}
